<?php 

//////// GET IDENTITY
$auth = Zend_Auth::getInstance();
if($hasIdentity = $auth->hasIdentity()) {
$user = $auth->getIdentity();}
	?>
<div id="container" class="margin15leftright">	
	<div id="msgErrArtist"></div>
	<form id="addArtist" enctype="application/x-www-form-urlencoded" method="post" class="form-horizontal aligncenter" onsubmit="submitFormAddArtist(); return false;"> <!-- action="/artist/addFromEvent" -->
	
	<input class="form-control" type="hidden" name="idArtist" id="idArtist" />
	
		<div class="form-group">
		 
		  <div class="col-sm-12">
		  <div class="labelMiniAdd">Pseudo</div>
			    <input type="text" class="form-control nameArtist" id="nameArtist" name="nameArtist" placeholder="John Hapta" required pattern="^[a-zA-Z0-9 _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ!@#$%^&*()_+\-=\[\]{};':\\|,.<>\/?]*$" onchange="upperCaseNameArtist(this.value)" />
				<span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
		  </div>
		</div>
		<div class="form-group">
		
		  <div class="col-sm-12">
				<div class="labelMiniAdd">Label</div>
			    <input type="text" class="form-control labelclass" id="label" name="label" placeholder="Hapta Records / Top Rec." pattern="^[a-zA-Z0-9 _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ.'/&-]*$" onchange="upperCaseLabel(this.value)" />
				<span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
		  </div>
		</div>
		<div class="form-group">
		  <div class="col-sm-12">
				<div class="labelMiniAdd">Pays</div>
			    <input type="text" class="form-control country" id="country" name="country" placeholder="France" pattern="^[a-zA-Z _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ&-]*$" onchange="upperCaseCountry(this.value)" />
				<span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
		  </div>
		</div>
  
		<div class="alignright">

			<button type="submit" id="submitbutton" onclick="trackOutboundLink('<?php echo Zend_Registry::get('City_Location'); ?> - <? echo $user->username ; ?> - Add Artist From Event Action');" class="btn btn-primary marginright35px">Envoyer</button>
		</div>
		
		
	</form>
</div>

<script type="text/javascript">
function initArtistsInput(){
	var parentNode = $('#idsArtist').parent();
	parentNode.html("");
	parentNode.html('<input id="idsArtist"  style="width:710px" >');
}

function submitFormAddArtist(){

	var nom = document.getElementById('nameArtist').value;
	var checkValidAddArtisteEvent = document.getElementById('nameArtist').validity.valid;
	
	if(nom == "" && checkValidAddArtisteEvent == false){
		$("#nameArtist").addClass('sendInvalid');
		return false;
	}
	if(nom != "" && checkValidAddArtisteEvent == false){
		$("#nameArtist").addClass('sendInvalid');
		return false;
	}
	
	var name = $('#nameArtist').val();
	var label = $('#label').val();
	var country = $('#country').val();
	var artists = eval($('#tagsArtist').val());

	$.ajax({
		type: 'POST',
		url: '/artist/addFromEvent',
		data: { name: name, label: label, country: country },
		success: function(data){
			if(data == 'INSERTION->Erreur'){
				$('#msgErrArtist').html('<div class="alert alert-danger">Un artiste du même nom existe déjà dans la base.</div>');
			} else {
				var artistToAdd = {};
				artistToAdd.name = data;
				artists.push(artistToAdd);
				$('#modalArtist').modal('hide');
				initArtistsInput();
				initArtistsField(artists);
			}
		}
	});
}
</script>
