<div id="container" class="margin15leftright">
  <form id="addSpot" enctype="application/x-www-form-urlencoded" method="post" action="/spot/addAdmin" class="form-horizontal" onsubmit="return verifAddSpotAdmin(this);">

    <div class="form-group">
     
      <div class="col-sm-12">
	  <div class="labelMiniAdd">Nom </div>
  	    <input type="text" class="form-control name" id="name" name="name" placeholder="Club Hapta" required pattern="^[a-zA-Z0-9 _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ&-']*$" onchange="upperCaseNom(this.value)" />
        <span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
      </div>
    </div>
    <div class="form-group">
     
      <div class="col-sm-12">
	  <div class="labelMiniAdd">Ville</div>
        <input type="text" class="form-control city" id="city" name="city" placeholder="Lyon 1" required pattern="^[a-zA-Z0-9 _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ&-']*$" onchange="upperCaseCity(this.value)" />
        <span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
      </div>
    </div>
    <div class="form-group">
     
      <div class="col-sm-12">
	  <div class="labelMiniAdd">Adresse</div>
        <input type="text" class="form-control address" id="address" name="address" placeholder="3, place de la hapta" onchange="upperCaseAdress(this.value)" />
      </div>
    </div>
    
    <div class="alignright">
	  <button class="btn btn-primary" type="submit">Envoyer</button>
	</div>

  </form>
</div>

<?php 
//$this->title = "Ajouter un club";
//$this->headTitle($this->title);
//echo $this->form; 
?>