<?php 

//////// GET IDENTITY
$auth = Zend_Auth::getInstance();
if($hasIdentity = $auth->hasIdentity()) {
$user = $auth->getIdentity();}
	?>
<div id="container" class="margin15leftright" >
<form id="ChangeRequestGenre" enctype="application/x-www-form-urlencoded" method="post" action="/genre/changeRequest" class="form-horizontal">

	<input type="hidden" name="idGenre" value="<?php if(isset($this->dataPopulate['idGenre'])) echo $this->dataPopulate['idGenre']; ?>" id="idGenre" /></dd>
	
	<div class="form-group">
			
			<div class="col-sm-12">
			<div class="labelMiniAdd">Genre</div>
				<input type="text" class="form-control nameGenre" id="nameGenre" name="nameGenre" placeholder="Nom du genre"  value="<?php if(isset($this->dataPopulate['nameGenre'])) echo $this->dataPopulate['nameGenre']; ?>" onchange="verifNomAddGenreAdmin(this.value)" readonly>
			</div>
	</div>
	
	<div class="form-group">
		  <div class="col-sm-12">
		  <div class="labelMiniAdd">Changement</div>
			    <input type="text" class="form-control changeRequest" id="changeRequest" name="changeRequest" placeholder="Changement souhaité" onchange="upperCaseChangeRequest(this.value)" >
		 </div>
	</div>
	
	
	<div class="alignright">
	       
			<button type="submit" id="submitbutton" class="btn btn-primary marginright35px" onclick="trackOutboundLink('<?php echo Zend_Registry::get('City_Location'); ?> - <? echo $user->username ; ?> - Change Genre Action');" >Envoyer</button>
		</div>
	
</form>
</div>