<?php 

//////// GET IDENTITY
$auth = Zend_Auth::getInstance();
if($hasIdentity = $auth->hasIdentity()) {
$user = $auth->getIdentity();}
	?>
	
<div class="row">

 <div class="col-md-6"><h1>Les Genres (<?PHP  echo count($this->genres);?>) </h1> </div>
  <div class="col-md-6 " ><div id="formAddbis" class="alignright paddingbot10px paddingtop10px">
	<a  class="btn-primary btn btn-lg" onclick="trackOutboundLink('<?php echo Zend_Registry::get('City_Location'); ?> - <? echo $user->username ; ?> - Add Genre Button');" id="linkFormAdd" data-toggle="modal" data-target="#myModal" onclick="getFormAdd();">Ajouter un Genre</a>
</div></div>
</div>
<?php if($this->notInsertable): ?>
	<div><div class="alert alert-danger">Un genre du même nom existe déjà dans la base.</div></div>
<?php endif; ?>

<div id="genres">
	

	<table class="table table-striped">
	<tr>
		<th>Nom &nbsp;<input id="searchGenre" class="width100 paddingleft5px" placeholder="Recherche" /></th>
		<th>Modification</th>
	</tr>
		
		<tr class="lastgenres"><td colspan="4" ><i>Par défault, vous retrouvez ci-dessous les 10 derniers ajouts de genre</i></td></tr>
		
		
	<?php foreach ($this->lastGenres as $genre) : ?>
			<tr class="lastgenres">
				<td><?php echo $this->escape($genre->getName()); ?></td>
				<td class="options"><a href="" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalChangeRequest" onclick="getFormChangeRequest(<?php echo $genre->getId(); ?>);">Demander une modification</i></a></td>
			
			</tr>
		<?php endforeach ?>
		
		<?php foreach ($this->genres as $genre) : ?>
			<tr hidden>
					<td class="name"><?php echo $this->escape($genre->getName()); ?></td>
					<td class="options"><a href="" data-toggle="modal" data-target="#modalChangeRequest" onclick="getFormChangeRequest(<?php echo $genre->getId(); ?>);">Demander une modification</i></a></td>
			</tr>
		<?php endforeach ?>
	</table>
</div>


<!-- Modal change request -->
<div class="modal fade" id="modalChangeRequest" tabindex="-1" role="dialog" aria-labelledby="modalChangeRequestLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title aligncenter" id="modalChangeRequestLabel">Demande de modification</h4>
      </div>
      <div class="modal-body" id="formChangeRequest">
       
      </div>
      
    </div>
  </div>
</div>

<!-- Modal add -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title aligncenter" id="myModalLabel">Création d'un Genre</h4>
      </div>
      <div class="modal-body" id="formAdd">
       
      </div>
     
    </div>
  </div>
</div>

<script type="text/javascript">


function getFormAdd(){
	$.get('/genre/add', 
		{},
		function(respond){
			$("#formAdd").html(respond); 
		}
	);
}

function getFormChangeRequest(idModif){
	var adressChange = '/genre/changeRequest/id/'+idModif;
	$.get(adressChange, 
		{},
		function(respond){
			$("#formChangeRequest").html(respond); 
		}
	);
}


function filterGenres(input){
	$('#genres .name').each(function(){
		$(".lastgenres").hide();
		
		if(input == ''){
			$(this).parent().hide();
			$(".lastgenres").show();
		} else {
			if($(this).html().toLowerCase().indexOf(input.toLowerCase()) == -1){
				$(this).parent().hide();
			} else {
				$(this).parent().show();
			}
		}
		
	});
	
}

$('#searchGenre').on('change textInput input', function(){
	filterGenres(this.value);
});

</script>