<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" style="text-align:center">Hapta <?php echo Zend_Registry::get('City_Location'); ?> Administration</h3>
                </div>
                <div class="panel-body">
                   <form id="login" enctype="application/x-www-form-urlencoded" method="post" action="" class="form-signin">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Nom d'utilisateur" name="username" id="username" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" id="password" type="password" value="">
                            </div>
							 <!-- Change this to a button or input when using this as a form 
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                           -->
                            <button class="btn btn-lg btn-primary btn-block" type="submit"  onclick="trackOutboundLink('<?php echo Zend_Registry::get('City_Location'); ?> - Connexion');" >Connexion</button>
                        </fieldset>
                    </form>
                </div>
                <?php if($this->errorMsg): ?>
                	<p style="text-align:center;color:red">Login ou mot de passe invalide</p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
