<div id="container">
	<form id="AjoutUser" enctype="application/x-www-form-urlencoded" method="post" action="/user/add" class="form-horizontal" onsubmit="return verifAddUsersAdmin(this);">

	<!--<input type="hidden" name="idGenre" value="<?php if(isset($this->dataPopulate['idGenre'])) echo $this->dataPopulate['idGenre']; ?>" id="idGenre" />-->
		
			<div class="form-group">
				<label for="username" class="col-sm-2 control-label">Pseudo</label>
				<div class="col-sm-10">
					<input type="text" class="form-control username" id="username" name="username" placeholder="Pseudo de l'utilisateur" required pattern="^[a-zA-Z _àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ&-]*$" onblur="upperCaseUsername(this.value)" />
					<span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
				</div>
			</div>
			<div class="form-group">
				<label for="password" class="col-sm-2 control-label">Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control password" id="password" name="password" placeholder="Mot de passe de l'utilisateur" required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}" />
					<span class="form_hint invalidPass" style="">Le mot de passe doit contenir 6 charactères avec 1 maj/min et une lettre.</span>
				</div>
			</div>
			<div class="form-group">
				<label for="password2" class="col-sm-2 control-label">Confirm</label>
				<div class="col-sm-10">
					<input type="password" class="form-control password2" id="password2" name="password2" placeholder="Confirmer le mot de passe de l'utilisateur" required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}" />
					<span class="form_hint invalidPass">Le mot de passe doit contenir 6 charactères avec 1 maj/min et une lettre.</span>
				</div>
			</div>
			<div class="form-group">
				<label for="email" class="col-sm-2 control-label">Email</label>
				<div class="col-sm-10">
					<input type="text" class="form-control email" id="email" name="email" placeholder="Email de l'utilisateur" required pattern="^[a-z0-9]+([_|\.|-]{1}[a-z0-9]+)*@[a-z0-9]+([_|\.|-]{1}[a-z0-9]+)*[\.]{1}[a-z]{2,6}$" />
					<span class="form_hint">Certains charactères spéciaux ne sont pas acceptés.</span>
				</div>
			</div>
			<div class="form-group">
				<label for="admin" class="col-sm-2 control-label">Admin ? </label>
				<div class="col-sm-10">
					<input type="checkbox" class=" admin" id="admin" name="admin" />
				</div>
			</div>
			
			<div class="alignright" >
				<button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
				<input type="submit" name="submit" id="submitbutton" value="Ajouter" class="btn btn-primary" />
			</div>

		</div>

	</form>
</div>