<div id="container">
	<form id="AjoutUser" enctype="application/x-www-form-urlencoded" method="post" action="/user/editAdmin" class="form-horizontal" onsubmit="return verifAddUsersAdmin(this)">

		<input type="hidden" name="id" value="<?php if(isset($this->dataPopulate['id'])) echo $this->dataPopulate['id']; ?>" id="id" />
	
		<div class="form-group">
			<label for="username" class="col-sm-2 control-label">Pseudo</label>
			<div class="col-sm-10">
				<input type="text" class="form-control username" id="username" name="username" placeholder="Pseudo de l'utilisateur" value="<?php if(isset($this->dataPopulate['username'])) echo $this->dataPopulate['username']; ?>" onblur="verifNomAddUsersAdmin(this.value)">
			</div>
		</div>
		<div class="form-group">
			<label for="password" class="col-sm-2 control-label">Password</label>
			<div class="col-sm-10">
				<input type="password" class="form-control password" id="password" name="password" placeholder="Mot de passe de l'utilisateur"onblur="verifPassAddUsersAdmin(this.value)">
			</div>
		</div>
		<div class="form-group">
			<label for="password2" class="col-sm-2 control-label">Confirm</label>
			<div class="col-sm-10">
				<input type="password" class="form-control password2" id="password2" name="password2" placeholder="Confirmer le mot de passe de l'utilisateur" onblur="verifPass2AddUsersAdmin(this.value)">
			</div>
		</div>
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<input type="text" class="form-control email" id="email" name="email" placeholder="Email de l'utilisateur" value="<?php if(isset($this->dataPopulate['email'])) echo $this->dataPopulate['email']; ?>" onblur="verifMailAddUsersAdmin(this.value)">
			</div>
		</div>
		<div class="form-group">
			<label for="admin" class="col-sm-2 control-label">Admin ? </label>
			<div class="col-sm-10">
				<input type="checkbox" class=" admin" id="admin" name="admin" <?php if(isset($this->dataPopulate['role'])): if($this->dataPopulate['role'] == "admin") echo "checked";  endif;?> />
			</div>
		</div>
		
		<div class="alignright" >
		 	<button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
			<input type="submit" name="submit" id="submitbutton" value="Modifier"  class="btn btn-primary" />
		</div>

	</form>
</div>